### ISSUE TITLE
Infracost comment commit

### ISSUE THREAD

**Issue by mpcabral** [infracost/infracost-jenkins#7] opened 2022-05-09 20:43 UTC
I am trying to make a pipeline to apply terraform script with jenkins
I did the job of checking and commenting on a pull request

But I would like to double check when a commit goes to master or when a PR is approved to master
But is not working

> stage('infracost') {
>             agent {
>                 docker {
>                     image 'infracost/infracost:ci-0.9'
>                     args "--user=root --entrypoint=''"
>                 }
>             }
>             environment {
>                 INFRACOST_API_KEY = credentials('jenkins-infracost-api-key')
>                 GITHUB_TOKEN = credentials('git_token')
>                 GITHUB_COMMIT = "${GIT_COMMIT}"
>                 GITHUB_REPO = "mpcabral/test-infracost"
>             }
>             steps {
>                 sh 'infracost breakdown --path plan.json --format json --out-file infracost.json'
>                 sh 'infracost comment github --policy-path infracost-policy.rego --path infracost.json --repo $GITHUB_REPO --commit $GITHUB_COMMIT --github-token $GITHUB_TOKEN'
>             }
>         }

        
I'm getting the following error:
`Type mismatch on variable $commitSha and argument oid (String! / GitObjectID)`

**Comment by alikhajeh1** [comment] 2022-05-09 23:51
@mpcabral it seems like this is a duplicate of https://github.com/infracost/infracost/issues/1635 so I'm going to close this but feel free to re-open it if I'm wrong.

**Closed by alikhajeh1** 2022-05-09 23:51 UTC
